### ISSUE TITLE
AttributeError: module 'ics.structures' has no attribute 's_extended_data_flash_header'

### ISSUE THREAD

**Issue by KyrieGuo123** [intrepidcs/python_ics#101]
AttributeError: module 'ics.structures' has no attribute 's_extended_data_flash_header'

**Comment by drebbe-intrepid** [comment]
@KyrieGuo123 Can you please provide your method of install, operating system, python version, `pip freeze` output, and any code outside the normal `import ics`?

**Comment by drebbe-intrepid** [comment]
I'm going to go ahead and close this out as I believe any issues you were possibly having were more than likely fixed with the latest release. If you are still having this issue in the future feel free to open this back up.
