### ISSUE TITLE
Add clang-format to list of dependencies

### ISSUE THREAD

**Issue by hollinsky-intrepid** [intrepidcs/python_ics#104]
Not 100% sure if it's a dependency for Windows, but for macOS and Linux you need to install clang-format.

On macOS, that's easiest with the homebrew package manager and `brew install clang-format`.

On Debian based (i.e. Ubuntu) Linux, you can do `sudo apt install clang-format`.

**Comment by drebbe-intrepid** [comment]
This check should probably be added to `setup.py` as its only needed when building the package from source. Windows has binaries so its usually never needed.

**Comment by drebbe-intrepid** [comment]
Fixed in v905.11
