### ISSUE TITLE
NeoVI Fire Device Not detected

### ISSUE THREAD

**Issue by danieldiaz7** [intrepidcs/python_ics#119]
After running this code:

```
import ics

ics.override_library_name("build/sub_direc/libicsneo/libicsneolegacy.so")

devices = ics.find_devices()

for device in devices:
    print(device.Name, device.SerialNumber)
```

It never prints out my NeoVI Fire 2 Device's name. When I have vehicle spy running, the device is recognized and I can connect to it. However, when I try to run this script, it's not able to find any device. Any help would be appreciated

**Comment by drebbe-intrepid** [comment]
@danieldiaz7 sorry for the late reply, can your provide more details on platform? Does this work if vehicle spy isn't running?

**Comment by drebbe-intrepid** [comment]
@danieldiaz7 I'm going to close this out assuming this issue has been resolved. Please feel free to re-open this if not.
