### ISSUE TITLE
how to send canfd msg with dls less than 8

### ISSUE THREAD

**Issue by YelaShady** [intrepidcs/python_ics#125]
I tried to send canfd msg with 8 bytes data used the example here:
https://github.com/YelaShady/python_ics/blob/master/examples/transmit_canfd_example.py
which data been sent as:
DATA_BYTES = tuple([x for x in range(7)])

but it sends all zero data,but I wish it should be [0,1,2,3,4,5,6].
Then when I tried with 
DATA_BYTES = tuple([x for x in range(9)])
it sends data like:
 ['0x0', '0x1', '0x2', '0x3', '0x4', '0x5', '0x6', '0x7', '0x8', '0x0', '0x0', '0x0']
Eventually I tried with
DATA_BYTES = tuple([x for x in range(62)])
it sends data like here,it has error length:
 ['0x0', '0x1', '0x2', '0x3', '0x4', '0x5', '0x6', '0x7', '0x8', '0x9', '0xa', '0xb', '0xc', '0xd', '0xe', '0xf', '0x10', '0x11', '0x12', '0x13', '0x14', '0x15', '0x16', '0x17', '0x18', '0x19', '0x1a', '0x1b', '0x1c', '0x1d', '0x1e', '0x1f', '0x20', '0x21', '0x22', '0x23', '0x24', '0x25', '0x26', '0x27', '0x28', '0x29', '0x2a', '0x2b', '0x2c', '0x2d', '0x2e', '0x2f', '0x30', '0x31', '0x32', '0x33', '0x34', '0x35', '0x36', '0x37', '0x38', '0x39', '0x3a', '0x3b', '0x3c', '0x3d', '0x0', '0x0']

**Comment by ic3man5** [comment]
@YelaShady Can you provide me with more information?

-Operating System
-Python version (32-bit/64-bit)
-python_ics version
-icsneo40.dll version
-Intrepid hardware being used
-Any extra details about your setup.

**Comment by drebbe-intrepid** [comment]
@YelaShady I'm going to assume this has been resolved so I'm closing this out. Feel free to re-open this if needed.
