### ISSUE TITLE
ics. ics.load_default_settings Failure

### ISSUE THREAD

**Issue by piyush-apple** [intrepidcs/python_ics#147]
>>> dev = ics.open_device("V46***")
>>> ics.load_default_settings(dev)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ics.ics.RuntimeError: Error: load_default_settings(): Failed to Retrieve address of function 'icsneoLoadDefaultSettings': dlsym(0x8811fc10, icsneoLoadDefaultSettings): symbol not found for library '@loader_path/libicsneolegacy.dylib'

**Comment by drebbe-intrepid** [comment]
@piyush-apple Can you let me know what version of `python_ics` you are using? This can be found by doing `pip show python_ics`.

This also looks like you are using a ValueCAN4-4 on MacOS. Can you provide details of your architecture also?

**Comment by drebbe-intrepid** [comment]
@piyush-apple I'm going to make the assumption your issue has been resolved. If not, please feel free to re-open this.
