### ISSUE TITLE
ics.find_devices() trhow 0xC0000005: Access Violation when USE_LECAGY_FIND_DEVICE is enabled

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#15]
When calling `ics.find_devices()` when `USE_LECAGY_FIND_DEVICE` is enabled, `0xC0000005: Access Violation` is raised.

This is caused by wrong `device_type` variable type.

https://github.com/intrepidcs/python_ics/blob/788aa3f76013712e53a9b96bcced2c4bb31a2b18/src/methods.cpp#L161

Potential fix:
```
PyObject* meth_find_devices(PyObject* self, PyObject* args, PyObject* keywords)
{
#ifndef USE_LEGACY_FIND_DEVICES
    PyObject* device_type = NULL;
#else
    unsigned long device_type = 0xFFFFBFFF;
#endif
    int ex_options = -1;
    char* kwords[] = { "type", "stOptionsOpenNeoEx", NULL };
    if (!PyArg_ParseTupleAndKeywords(args, keywords, arg_parse("|Oi:", __FUNCTION__),
                                     kwords, &device_type, &ex_options)) {
        return NULL;
    }
    ice::Library* lib = dll_get_library();
    if (!lib) {
        char buffer[512];
        return set_ics_exception(exception_runtime_error(), dll_get_error(buffer));
    }
    NeoDevice devices[255];
    int count = 255;
    try
    {
#ifndef USE_LEGACY_FIND_DEVICES
        // Get the list of device types
```

**Comment by pierreluctg** [comment]
FYI @drebbe-intrepid

**Comment by drebbe-intrepid** [comment]
Thanks for catching this, I'll correct it ASAP.

**Comment by drebbe-intrepid** [comment]
Should be fixed now, I was planning on 2.9 being the last release of 802 VSPY3 branch. Since you need to compile from source I don't see a new release being needed for this fix.

Master Branch is now going to reflect VSPY3 803 branch.

**Comment by pierreluctg** [comment]
@drebbe-intrepid can you make a new release to pypi?

Thank you

**Comment by drebbe-intrepid** [comment]
Can you give me more details why you need this flag enabled? It should work without it. I was considering enabling this flag by default in the 2.x branch.

I am planning on doing a new release as I've found another issue elsewhere.

**Comment by pierreluctg** [comment]
Hi @drebbe-intrepid the last dll version I got from https://www.intrepidcs.com/support/support-resources/ is 3.8.2.109 this is apparently the old style DLL.

**Comment by drebbe-intrepid** [comment]
Thanks for the response.
The default build without USE_LEGACY_FIND_DEVICES flag tries to call the new style function. If it doesn't exist, it will fallback to the old style function in this case. Only reason I implemented USE_LEGACY_FIND_DEVICES was for special corner cases where performance would be an issue of calling find_devices with the extra failing call.

The reason I was debating enabling the flag by default in the 2.x release branch was to remove any doubt I broke something. I'll do some more testing on my end before next release.

**Comment by drebbe-intrepid** [comment]
@pierreluctg 2.10 just released, let me know if you have any issues.

**Comment by pierreluctg** [comment]
@drebbe-intrepid, it's better now `ics.find_devices()` no longer cause issue.

However, `ics.find_devices(a_ics_device_type)` will raise an exception from https://github.com/intrepidcs/python_ics/blob/v802/src/methods.cpp#L155

and using `ics.find_devices([a_ics_device_type])` will not do any device type filtering because `legacy_dev_type` will keep the default value.

**Comment by drebbe-intrepid** [comment]
python test_find_devices.py -v
test_default_parameters (__main__.TestFindDevicesLegacy) ... ok
test_default_parameters_time (__main__.TestFindDevicesLegacy) ... ok
test_find_fire2 (__main__.TestFindDevicesLegacy) ... ok
test_find_fire2_and_vcan3 (__main__.TestFindDevicesLegacy) ... ok
test_find_vcan3 (__main__.TestFindDevicesLegacy) ... ok
test_default_parameters (__main__.TestFindDevicesNewStyle) ... ok
test_default_parameters_time (__main__.TestFindDevicesNewStyle) ... ok
test_find_fire2 (__main__.TestFindDevicesNewStyle) ... ok
test_find_fire2_and_vcan3 (__main__.TestFindDevicesNewStyle) ... ok
test_find_vcan3 (__main__.TestFindDevicesNewStyle) ... ok
test_default_parameters (__main__.TestFindDevicesNewStyleWithLegacyDLL) ... ok
test_default_parameters_time (__main__.TestFindDevicesNewStyleWithLegacyDLL) ... ok
test_find_fire2 (__main__.TestFindDevicesNewStyleWithLegacyDLL) ... ok
test_find_fire2_and_vcan3 (__main__.TestFindDevicesNewStyleWithLegacyDLL) ... ok
test_find_vcan3 (__main__.TestFindDevicesNewStyleWithLegacyDLL) ... ok

----------------------------------------------------------------------
Ran 15 tests in 4.795s

OK

**Comment by drebbe-intrepid** [comment]
@pierreluctg 2.11 just released. Should be fixed 100% now.

**Comment by pierreluctg** [comment]
Two little issues left...

- Device type filtering with new style find_devices arguments with legacy DLL is broken.
    - The unit test pass because the expect the filtering to be broken... Is that expected https://github.com/intrepidcs/python_ics/blob/master/test/test_find_devices.py#L65
- `ics.NEODEVICE_*` argument need to be converted to `long` to be used as a device type filter in Python 2.x since `int != long` in Python 2.x and the `ics.NEODEVICE_*` are int type.

In Python 2.x the following code:
```python
import ics
ics.find_devices(ics.NEODEVICE_FIRE2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-7ae0dcb3a391> in <module>()
----> 1 ics.find_devices(ics.NEODEVICE_FIRE2)

RuntimeError: Error: _convertListOrTupleToArray(): _convertListOrTupleToArray() was passed neither a list or tuple
```
the following code works:
```python
import ics
ics.find_devices(long(ics.NEODEVICE_FIRE2))
```

**Comment by drebbe-intrepid** [comment]
@pierreluctg thanks for finding this, completely overlooked 2.7 int/long changes. Seems I can't get anything right this week...

**Comment by drebbe-intrepid** [comment]
```
All versions are passing now, will be uploading 2.12 here shortly.

================================================================== 
PYTHON27  
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 5.580s

OK
================================================================== 
PYTHON33 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 5.673s

OK
================================================================== 
PYTHON34 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 5.534s

OK
================================================================== 
PYTHON35 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 5.588s

OK
================================================================== 
PYTHON36 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 5.529s

OK
================================================================== 
PYTHON27-64 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 4.432s

OK
================================================================== 
PYTHON34-64 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 4.571s

OK
================================================================== 
PYTHON35-64 
================================================================== 
...............
----------------------------------------------------------------------
Ran 15 tests in 4.484s

OK

```

**Comment by drebbe-intrepid** [comment]
for future reference the various issues here are from 2.9-2.11 release.
