### ISSUE TITLE
Unable to open device

### ISSUE THREAD

**Issue by carineapig** [intrepidcs/python_ics#152]
Hi, I am able to find the device, but I cannot open the device. When I call ics.open_device, I get this error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ics.ics.RuntimeError: Error: open_device(): icsneoOpenDevice() Failed
```

**Comment by drebbe-intrepid** [comment]
@carineapig Which operating system are you using? If its linux its probably a permissions issue with udev.

**Comment by carineapig** [comment]
yes it is ubuntu 22.04. How can I solve?

**Comment by 8Klaro8** [comment]
I got the same error by running my python file which includes the next:
`import can
mybus = can.interface.Bus(bustype="neovi",channel=1,bitrate=500000)`

Error:
`ics.ics.RuntimeError: Error: open_device(): icsneoOpenDevice() Failed
    ics.close_device(self.dev)
ics.ics.RuntimeError: Error: close_device(): icsneoClosePort() Failed`

Info:
I am on windows, using git bash.
If there is any clue, please share it.
