### ISSUE TITLE
get_library_path() returns unresolved variable ORIGIN as part of the string

### ISSUE THREAD

**Issue by kevinsikes** [intrepidcs/python_ics#153]
Calling `get_library_path()` with version 908.12 returns "libicsneolegacy.so"
Calling `get_library_path()` with version 911 or later returns "${ORIGIN}/libicsneolegacy.so"

Expected behavior: No unresolved variable names would come back as part of the path string.

I am using an older libicsneo built from commit gf1d9be1 (libicsneo-v0.2.0-177-gf1d9be1_x86_64.deb is our internal package name), in case this makes a difference.

**Comment by drebbe-intrepid** [comment]
@kevinsikes Thank you for this report. I'll work on getting this resolved. This was a hack I had to put in place for `LD_LIBRARY_PATH` to be able to find the shared library when its next to the executable. I don't believe its possible to expand this variable so I'm not sure the proper way to fix this. Would having `${ORIGIN}` dropped be okay in your use case?

**Comment by kevinsikes** [comment]
Stripping off `${ORIGIN}` from the returned string seems sensible.  Thanks for addressing!
