### ISSUE TITLE
Problem loading icsneo40.dll Library

### ISSUE THREAD

**Issue by xuleixie** [intrepidcs/python_ics#154]
error code is: 193
Problem loading Library
Make sure icsneo40.dll is installed and accessable

**Comment by drebbe-intrepid** [comment]
@xuleixie error 193 is:
```
ERROR_BAD_EXE_FORMAT
193 (0xC1)
%1 is not a valid Win32 application.
```

This means your icsneo40.dll architecture is different from your python version (32-bit vs 64-bit)

**Comment by xuleixie** [comment]
https://cdn.intrepidcs.net/support/neoVIDLL/VCNewneoVI.zip   this project can't load library,but my another project load successfully

**Comment by xuleixie** [comment]
I test on a new win10 virtual machine,load successfully, it not have python env
![image](https://github.com/intrepidcs/python_ics/assets/26809087/c4e96520-500a-4de9-a218-cadac3349bfd)
so I guess because OS version too high

**Comment by xuleixie** [comment]
this version OS load fail, you should focus on
![image](https://github.com/intrepidcs/python_ics/assets/26809087/6cb7c89a-ce47-4de8-ac99-4951824722d6)

**Comment by drebbe-intrepid** [comment]
@xuleixie This looks like a very old version of icsneo40.dll that was pre windows 10. Without seeing SpyContrlServer.exe source code and a more detailed error log I don't really know how to help further.

**Comment by xuleixie** [comment]
this is my source code https://github.com/xuleixie/SpyContrlServer
could you run it and help me? and do you have new version icsneo40.dll?

**Comment by drebbe-intrepid** [comment]
@xuleixie this looks like its out side the scope of `python_ics`. Please contact icssupport@intrepidcs.com and our support team will be happy to assist you further! I'm going to go ahead and close this out for now.
