### ISSUE TITLE
API support to get Network Statistics of CAN channel

### ISSUE THREAD

**Issue by amoljamble1** [intrepidcs/python_ics#155]
Hi,

I need python alternative for below c structure inside the vspy.c.

// Network Statistics
typedef struct {
    unsigned int iCount;  /// count of messages on network
    unsigned int iRate; /// messages per second
    double dPercentUse; /// current bus utilization 
    unsigned int iMaxRate;    /// maximum messages per second
    double dMaxPercentUse;   /// maximum bus utilization
    unsigned int iErrorCount;   /// number of errors on a network
    unsigned int iTxCount;       /// number of messages transmitted on a network
    unsigned int iErrorRate; /// errors per second
    unsigned int iTxRate;        /// transmissions per second
    unsigned int iTxBufferFill;  /// current network buffer fill level
    unsigned int iCANTxErrCount;  /// transmit CAN errors
    unsigned int iCANRxErrCount;  /// receive CAN errors
} NetworkStats; 

Thanks,
Amol

**Comment by drebbe-intrepid** [comment]
@amoljamble1 Thanks for the request. Unfortunately this is part of Vehicle Spy 3's C code interface and requires vehicle spy to function correctly.  You'll have to implement this yourself on the python side unfortunately.
