### ISSUE TITLE
RAD-Moon 2: fails to open with libicsneo on linux

### ISSUE THREAD

**Issue by jacobschaer** [intrepidcs/python_ics#162]
I need to be able to control some settings on a radmoon programatically and was hoping to be able to do it with Python-ICS API. I was able to get what I need on Windows, but not on Linux. Issue was confirmed by support and is supposedly due to a discrepancy between icsneo40.dll and libicsneo capabilities.

On Windows:

    Install ICS Hardware Installation Kit: https://cdn.intrepidcs.net/updates/files/RP1210KitInstall.zip
    Install python-ics python package
        pip install python-ics
        pip freeze
            python-ics==912.4post1
    In python I can
        import ics
        ics.FindNeoDevices()
        (<ics.ics.NeoDevice RAD-Moon 2 RM5913>,)
        device = ics.open_device(ics.FindNeoDevices()[0])

This is fine.

On Ubuntu 18.04 and Ubuntu 23 with Python 3.8 and 3.11, the first command (FindNeoDevices()) enumerates the device properly but attempts to call open_device() fail with

ics.ics.RuntimeError: Error: open_device(): icsneoOpenDevice() Failed

I tried with the supplied libicsneolegacy.so as well as compiled from source for python-ics=910.10.post6 - same result. 

I tried running as root and ensured I had installed the 99-instrepidcs.rules

**Comment by drebbe-intrepid** [comment]
@jacobschaer If you run this script as root does it work? This would point to the rules not being applied correctly.

**Comment by jacobschaer** [comment]
Any ideas on what PIP version to use? I'm happy to try a dev build or something.

**Comment by drebbe-intrepid** [comment]
I've confirmed internally that latest isn't working.

python_ics is on https://github.com/intrepidcs/libicsneo/commit/9ef93eb73e1ada72ccc7a571744b9db1a564f18b and we need to be on at least https://github.com/intrepidcs/libicsneo/commit/6c93fc839b42213f989efb7a04a104962cdd07b2

I'll try to get the packages updated today and confirm RAD-Moon2 is working for you. Sorry for the issues here.

**Comment by jacobschaer** [comment]
Any updates on this issue?

**Comment by drebbe-intrepid** [comment]
@jacobschaer This is in progress right now. There should be a fix coming shortly. Thanks for your patience with this matter so far.

**Comment by subrivian** [comment]
Can you explain to me what I need to do to use these updates?

On Ubuntu 22.04:

1. sudo apt-get install flex bison clang
2. python3.8 -m venv venv
3. source venv/bin/activate
4. git clone https://github.com/intrepidcs/python_ics
5. cd python_ics
6. git submodule update --init
7. python -m pip install .
8. python radmoon.py

Traceback (most recent call last):
  File "radmoon.py", line 68, in <module>
    devices = ics.FindNeoDevices()
ics.ics.RuntimeError: Error: find_devices(): Failed to Retrieve address of function 'icsneoFindDevices': {...}/venv/lib/python3.8/site-packages/ics/ics.cpython-38-x86_64-linux-gnu.so: undefined symbol: icsneoFindDevices for library '${ORIGIN}/libicsneolegacy.so'


I tried just pip install python_ics and it offered an older version

**Comment by drebbe-intrepid** [comment]
@subrivian I've reproduced this locally. Looking into it now. Master is currently broke. 

```python
>>> ics.override_library_name(r'/home/drebbe/dev/python_ics/.venv/lib/python3.11/site-packages/ics/libicsneolegacy.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ics.ics.RuntimeError: Error: override_library_name(): Failed to open library '/home/drebbe/dev/python_ics/.venv/lib/python3.11/site-packages/ics/libicsneolegacy.so': /home/drebbe/dev/python_ics/.venv/lib/python3.11/site-packages/ics/libicsneolegacy.so: undefined symbol: dbus_connection_read_write
```

**Comment by subrivian** [comment]
What's interesting is it works fine if I used the wheel from the github build artifacts for the MR you linked. So, hopefully once you do a release to PyPi this will be a non-issue but would be nice to be able to build locally and get a workign package. Thanks

**Comment by drebbe-intrepid** [comment]
@subrivian This issue should be resolved now. I was able to fix it locally on my machine.

@jacobschaer RAD-Moon2 should work now. I'll be providing an official release to PIP hopefully soon but you can always grab the artifacts / wheels for now if needed right away.

**Comment by drebbe-intrepid** [comment]
Closing this issue as complete, please feel free to re-open this if there is still an issue. latest version on PyPI should be functional.
