### ISSUE TITLE
Add Python37 to v802 branch

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#18]
Hi @drebbe-intrepid, can you port https://github.com/intrepidcs/python_ics/commit/d07203cd20c1c81f4664cc01f2c405eb27e9657b to the v802 branch?

**Comment by drebbe-intrepid** [comment]
Yes, I'm not really happy with that commit. I'll try to get it ported here soon. I was waiting for an actual release and not an RC to continue with this.

**Comment by drebbe-intrepid** [comment]
Support was added in 2.15 and uploaded.
