### ISSUE TITLE
Creating .exe from code using python-ics

### ISSUE THREAD

**Issue by BrandonDombrowski** [intrepidcs/python_ics#193]
I've been attempting to create an executable file from my code, but I've been getting an error as shown below:

AttributeError: module 'ics.structures' has no attribute 's_extended_data_flash_header'

I've seen #99 and did some digging to find that's the first item in the hiddenimports.py script, but including that doesn't seem to solve my issue. Any help would be greatly appreciated!

**Comment by drebbe-intrepid** [comment]
Sorry for the late response, please see https://python-ics.readthedocs.io/en/master/index.html#pyinstaller
