### ISSUE TITLE
Please provide example to clear previously set LIN frame data

### ISSUE THREAD

**Issue by nuts4coffee** [intrepidcs/python_ics#199]
We followed the example examples/transmit_lin_example.py to simulate LIN messages from the Slave node. After the message is sent, the frame data is saved on the Neovi hardware, and sent to the LIN Master node automatically when the Master sends the header-only frame to request the frame data.
The question is, how do we clear the data for a given frame. The use case is we want to simulate the case when certain frames are not sent by the Slave nodes, and check the expected errors are indicated by the Master.

**Comment by drebbe-intrepid** [comment]
@nuts4coffee you should be able to set the data bytes to empty and it should clear it.

**Comment by drebbe-intrepid** [comment]
Yes the Data attribute of `ics.SpyMessage` can be set to an empty tuple.

```python
m = ics.SpyMessge()
m.Data = ()
```

**Comment by nuts4coffee** [comment]
The provided solution works. Thank you.
