### ISSUE TITLE
ics.open_device iOptions arguments

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#20]
Hi @drebbe-intrepid, while looking at the documentation for [ics.open_device](http://python-ics.readthedocs.io/en/2.15/#ics.open_device), I saw the there is a argument called `iOptions` with unclear documentation and reference to `DEVICE_OPTION_* defines` that is not found in `python-ics`.

Can you clarify how the `iOptions` is supposed to be used and what are the possible values.

Thank you

**Comment by drebbe-intrepid** [comment]
@pierreluctg this is more for internal use / customer specific options. Majority of the options I can't really expose publicly.

This is really the only one I can show you:
`#define DEVICE_OPTION_DISABLE_AUTO_UPDATE (0x00000002)`
and it bypasses updating the firmware in the device (I don't recommend using).

**Comment by pierreluctg** [comment]
@drebbe-intrepid, if I look at the online documentation for [OpenNeoDevice Method - intrepidcs API](https://cdn.intrepidcs.net/support/neoVIDLL/OpenNeoDevice.htm), there is a argument called `bSyncToPC` not exposed here in `python-ics`. Is this a `DEVICE_OPTION_*` that can be used here?

**Comment by drebbe-intrepid** [comment]
@pierreluctg  `bSyncToPC` is a boolean value and after quickly examining the code the default value is not correct. `iOptions` should be set to `1` to set `bSyncToPc` to `1`.

The find and open methods are going to undergo a rewrite here hopefully sooner than later as there is another API being introduced again and the code has become a giant pile of spaghetti code I'm not happy with. Thank you for finding this for me.
