### ISSUE TITLE
transmit_canfd_example.py not working

### ISSUE THREAD

**Issue by Akshaypkumar0077** [intrepidcs/python_ics#201]
transmit_canfd_example.py not working, but transmit_can_example.py is working. We have commented out receiver side and checked.
Error showing is as follows:
ics.transmit_messages(device, msg)
[ics.ics.RuntimeError: Error: transmit_messages(): icsneoTxMessages() Failed

We are using ValueCAN3 for testing.

**Comment by pierreluctg** [comment]
@Akshaypkumar0077 the ValueCAN 3 do not support CAN FD
