### ISSUE TITLE
Failed to install latest 2.15.

### ISSUE THREAD

**Issue by zhihongliuus** [intrepidcs/python_ics#22]
When trying to upgrade from 2.6 to 2.15. I got following compile error:

                      ^
    src/methods.cpp:2157:108: warning: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     #define _set_fire_settings(handle, settings, save) __set_fire_settings(handle, settings, save, __FUNCTION__);
                                                                                                                ^
    src/methods.cpp:2440:20: note: in expansion of macro ‘_set_fire_settings’
                 return _set_fire_settings(handle, settings, save_to_eeprom);
                        ^
    src/methods.cpp:2084:18: warning:   initializing argument 4 of ‘PyObject* __set_fire_settings(void*, PyObject*, int&, char*)’ [-fpermissive]
     static PyObject* __set_fire_settings(ICS_HANDLE handle, PyObject* settings, int& save, char* func_name)
                      ^
    src/methods.cpp: In function ‘PyObject* meth_get_library_path(PyObject*)’:
    ****src/methods.cpp:4127:49: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
             return Py_BuildValue("s", lib->getPath());****
                                                     ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of python-ics
Command "/home/yz2q7g/pyauto/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-U2_A0G/python-ics/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-XmLaC6/install-record.txt --single-version-externally-managed --compile --install-headers /home/yz2q7g/pyauto/include/site/python2.7/python-ics" failed with error code 1 in /tmp/pip-install-U2_A0G/python-ics/

Could you help to take a look?

Thanks,
Frank

**Comment by drebbe-intrepid** [comment]
@zhihongliuus Can you let me know what distribution you are running and what compiler version you are using?

This looks like an error on my part but I'm surprised it compiles at all on my side. Once I get this information I should be able to reproduce and fix it.

**Comment by zhihongliuus** [comment]
@drebbe-intrepid 
Please see my below environment information:

- Ubuntu: 4.4.0-112-generic #135~14.04.1
- x86_64-linux-gnu-gcc: x86_64-linux-gnu-gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
- Python: 2.7
- pip: 18.0

**Comment by zhihongliuus** [comment]
@drebbe-intrepid 

Awesome! I just installed it successfully. Thank you for the quick fix!

**Comment by drebbe-intrepid** [comment]
@zhihongliuus glad to hear it works!
