### ISSUE TITLE
Please add change log

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#26]
There is no version change log.
So somebody maybe  confused about upgrading and other issues, e.g., in iso15765_example.py
`    # CmISO157652TxMessage.flags bitfield union isn't implemented as of 2.12, we need to do it manually.
    msg.flags = 0`
Now the lastest version is 2.15, so we have to check source to determine whether msg.flag is implemented.

**Comment by drebbe-intrepid** [comment]
Done.
