### ISSUE TITLE
RuntimeError: icsneoISO15765_ReceiveMessage() not found in icsneo40.dll

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#27]
This function is not defined in icsneo40.dll v3.6 & v3.7
So it's better to add icsneo40.dll  version requirement in document and check it after loading than throw exception.

> ics.RuntimeError: Error: iso15765_receive_message(): Failed to Retrieve address of function 'icsneoISO15765_ReceiveMessage': Windows Error #127 for library 'icsneo40.dll'

**Comment by drebbe-intrepid** [comment]
I'm going to close this out after further thought, the python_ics module started after v600/700 versions, I would consider an exception thrown okay in this case.
