### ISSUE TITLE
ISO15765 padding not works

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#28]
![image](https://user-images.githubusercontent.com/20385450/47290725-6884a600-d633-11e8-8354-013f0685a7b4.png)

- icsneo40.dll version: 3.8.2.111, 32 bit
- python-ics: 2.15
- Python: 3.7.1, 32 bit
- OS: Windows 7 SP1, 64 bit

Here is my code which modified from iso15765_example.py

`@dataclass
class ECU:
    name: str
    txid: int
    rxid: int

    txmsg: ics.CmISO157652TxMessage = ics.CmISO157652TxMessage()
    rxmsg: ics.CmISO157652RxMessage = ics.CmISO157652RxMessage()
    net: int = ics.NETID_HSCAN
    padding: int = 0x00
    blocksize: int = 100
    fstimeout: int = 0x10
    fswait: int = 0x3000
    cftimeout: int = 1000
    stmin: int = 10

    def __post_init__(self):
        self.txmsg.vs_netid = self.net
        self.txmsg.id = self.txid
        self.txmsg.fc_id = self.rxid
        self.txmsg.fc_id_mask = 0xFFF
        self.txmsg.padding = self.padding
        self.txmsg.blockSize = 0
        self.txmsg.fs_timeout = self.fstimeout
        self.txmsg.fs_wait = self.fswait
        self.txmsg.stMin = 0
        self.txmsg.flags = (1 << 5) | (8 << 23)
        # self.txmsg.flowControlExtendedAddress = 0xFE

        self.rxmsg.vs_netid = self.net
        self.rxmsg.id = self.rxid
        self.rxmsg.id_mask = 0xFFF
        self.rxmsg.fc_id = self.txid
        self.rxmsg.padding = self.padding
        self.rxmsg.blockSize = self.blocksize
        self.rxmsg.cf_timeout = self.cftimeout
        self.rxmsg.stMin = self.stmin
        self.rxmsg.flags = (1 << 5) | (1 << 4)
`

`
def main(args):
    logfmt = '%(asctime)s    %(message)s'
    logging.basicConfig(level=args.logLevel, format=logfmt)

    net = args.net
    ecu = ECU('ICM', 0x760, 0x768)
    data = [0x10, 0x40]
    
    ecu.txmsg.data = data
    ecu.txmsg.num_bytes = len(data)

    device = ics.open_device()
    ics.iso15765_enable_networks(device, net)
    ics.iso15765_receive_message(device, net, ecu.rxmsg)
    if ics.iso15765_transmit_message(device, net, ecu.txmsg, ecu.fswait):
        waitms = (len(data) / 8) * ecu.txmsg.fs_timeout
        print(f'Waiting {waitms} ms')
        time.sleep((waitms / 1000) + 0.5)
    else:
        print(ics.get_error_messages(device))
    get_iso15765_msgs(device)

    ics.iso15765_disable_networks(device)`

**Comment by keelung-yang** [comment]
It's a bug for single frame message.
According to 'ISO 15765-2:2011(E) 9.4.2.1 CAN frame data padding':
> If this solution is used, the DLC is always set to 8, even if the N_PDU to be transmitted is shorter than 8 bytes. The sender has to pad any unused bytes in the frame. In particular, this can be the case for an SF, FC frame or the last CF of a segmented message
 
I tested iso15765_example.py, changed number_of_bytes to 4 and 9, the output:

![image](https://user-images.githubusercontent.com/20385450/47331390-6d3a7000-d6ae-11e8-89bf-e2637e1e0e48.png)

**Comment by drebbe-intrepid** [comment]
@keelung-yang Sorry I missed all your issue reports, seems like my email notifications aren't working like they should anymore...

I have a lot on my list currently, hopefully sometime in January I can check everything off my list.

**Comment by syntroniks** [comment]
I'm encountering this issue as well.
Thanks for the update @drebbe-intrepid

**Comment by drebbe-intrepid** [comment]
@syntroniks Thank you for the information. I'll let you know, if I find anything. If you are in possession of any other devices like a FIRE2, testing on those would be appreciated.

**Comment by syntroniks** [comment]
Yes, I've got one of your higher-end interfaces. I'll give that a shot
first thing in January and report back.

**Comment by drebbe-intrepid** [comment]
@syntroniks Please update to at least 3.8.2.111. This should hopefully fix your issue.

@keelung-yang It looks like you are using the same device and neoVI Server. This shouldn't work correctly with the example, can you please provide full source to your modifications?

**Comment by drebbe-intrepid** [comment]
closing this out due to lack of activity. Please re-open if needed.

**Comment by syntroniks** [comment]
Thanks for updating David, I don't have a license current enough to upgrade to that version of Vehicle Spy. I'll try once we renew and I suspect everything will work as intended.

Again, thanks for your investigation and assistance.

**Comment by djcatter** [comment]
We were able to repeat this with python 2.7 with the latest version of VSpy 3.9.1.27 and DLLs. Can try  on a new ValueCAN4 if that would help. Just set the demo script to 2. 

Note that the padding does fill out in the Flow Control Frame.


> Opening Device ValueCAN3 135678 (Open Client handles: 0)...
Opened Device ValueCAN3 135678.
Opening Device ValueCAN3 133157 (Open Client handles: 0)...
Opened Device ValueCAN3 133157.
Setting up iso15765 message on ValueCAN3 133157...
Setup iso15765 message on ValueCAN3 133157.
Transmitting iso15765 message on ValueCAN3 135678...
Transmitted iso15765 message on ValueCAN3 135678.
Received 1 messages with 0 errors.
Message #1
        ArbID: 0x7e0L   Data: ['0x2', '0x0', '0x1']


>Name: python-ics
Version: 4.3
Summary: Library for interfacing with Intrepid devices in Python
Home-page: https://github.com/intrepidcs/python_ics/
