### ISSUE TITLE
Typo in methods.h

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#32]
Should be _meth_get_bit_rate_ ?

![image](https://user-images.githubusercontent.com/20385450/50430766-e6e61880-0900-11e9-89e9-58e45305740d.png)

**Comment by drebbe-intrepid** [comment]
@keelung-yang This is a typo but icsneoGetBitRate() doesn't exist so there is nothing I can do here. If this is something you require I can pass it on internally as an enhancement.

**Comment by drebbe-intrepid** [comment]
Closing, from lack of response and duplicate has been removed.
