### ISSUE TITLE
Is BitRate an integer or ics.BPS* in set_bit_rate()?

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#33]
BitRate parameter is not documented here.
![image](https://user-images.githubusercontent.com/20385450/50431040-b99a6a00-0902-11e9-8d46-cf0994742316.png)

**Comment by drebbe-intrepid** [comment]
Please see https://cdn.intrepidcs.net/support/neoVIDLL/SetBitRate.htm for more documentation on icsneoSetBitRate()

python_ics documentation should be clearer.

**Comment by drebbe-intrepid** [comment]
Fixed, closing out.
