### ISSUE TITLE
libicsneoapi.so Limitations.

### ISSUE THREAD

**Issue by XhantorzD** [intrepidcs/python_ics#34]
The Windows DLL file contains all of the supported functions for the Python ICS package, however, when building for Linux, following the guide here https://github.com/intrepidcs/icsneoapi  to make the libicsneoapi.so share object library, only a few functions are available, such as:

00003f10 T icsneoClosePort
00003fc0 T icsneoFindNeoDevices
00003f3c T icsneoFreeObject
00003f4c T icsneoGetMessages
00004004 T icsneoGetTimeStampForMsg
000041d4 T icsneoInitializeAPI
000040fc T icsneoOpenNeoDevice
000040d4 T icsneoSerialNumberFromString
00004058 T icsneoSerialNumberToString
00003e74 T icsneoShutdownAPI
00003f88 T icsneoTxMessages
00004038 T icsneoWaitForRxMessagesWithTimeOut
00001a98 T _init

Whereas the DLL file has all of the functions:

![dll](https://user-images.githubusercontent.com/46224075/50519862-46742d80-0a93-11e9-9db0-32c8f4816ea8.PNG)
...(there is even more functions)

I'am able to run some functions as shown below, but not all of them:

```
import ics
dev = None;
devices = ics.find_devices()
for device in devices:
    print(device.Name, device.SerialNumber)
    if device.SerialNumber == XXXXXX:
        ics.open_device(device)
        dev = device;
        break;
if dev != None:
    #print(ics.get_messages(dev,False,1000))
    print(ics.get_rtc(dev))

print("End")
```
**Output:** 
```console
neoVI FIRE XXXXXX
Traceback (most recent call last):
  File "device.py", line 12, in <module>
    print(ics.get_rtc(dev))
ics.RuntimeError: Error: get_rtc(): Failed to Retrieve address of function 'icsneoGetRTC': /usr/lib/arm-linux-gnueabihf/libicsneoapi.so: undefined symbol: icsneoGetRTC for library 'libicsneoapi.so'
```

I've looked into replacing the lib with the libicsneoAPI.so.0.1.3 lib, that seems to contain all the functions, hower I'm using an arm processor and it cannot read this shared object library as it was probably compiled on an x86/x64 processor and there is no source code for this. 

So I guess my question is, is there something I'm missing to get this functioning on an arm processor, or if not would it be possible to have the libicsneoAPI.so.0.1.3 compiled for an armhf processor?

I do realize this may be better off posted on the https://github.com/intrepidcs/icsneoapi repo, however, my end goal is to get the python_ics package working on my arm device.

Thank you for the work you guys do on the python side of things,
Thanks,
Jo.

**Comment by drebbe-intrepid** [comment]
@XhantorzD Thank you for this bug report. The linux side does have many limitations unfortunately and libicsneoAPI.so.0.1.3 is extremely old and shouldn't be used.

The future is this project but I have yet to support python with it:
https://github.com/intrepidcs/libicsneo 

This library has legacy support for icsneo40/icsneoAPI but I'm not sure how well it will work currently with python_ics.

https://github.com/intrepidcs/libicsneo/blob/master/include/icsneo/icsneolegacy.h

**Comment by drebbe-intrepid** [comment]
@XhantorzD I can confirm basic functionality works with the new API on windows at least.

You'll have to call ics.override_library_name() to utilize the new library. I'm guessing it is probably called libicsneolegacy.so on linux but not really sure at this point.

**Comment by XhantorzD** [comment]
Awesome, thanks for your help @drebbe-intrepid

**Comment by XhantorzD** [comment]
> @XhantorzD I can confirm basic functionality works with the new API on windows at least.
> 
> You'll have to call ics.override_library_name() to utilize the new library. I'm guessing it is probably called libicsneolegacy.so on linux but not really sure at this point.

ics.RuntimeError: Error: find_devices(): Failed to open library 'libicsneoapi.so': /usr/lib/x86_64-linux-gnu/libicsneolegacy.so: undefined symbol: _ZN6icsneo10NeoVIFIRE218SUPPORTED_NETWORKSE   

Do you have an idea what may be causing this?

**Comment by hollinsky-intrepid** [comment]
We should be all set now as of intrepidcs/libicsneo@c313801, see intrepidcs/libicsneo#1
