### ISSUE TITLE
python-ics 4.0 does not have the Python 2.x tags removed

### ISSUE THREAD

**Issue by ovianao** [intrepidcs/python_ics#44]
According to the 4.0 release, support for Python 2.7 was dropped:
https://github.com/intrepidcs/python_ics/releases/tag/v4.0

However, looking at the code here, the Python 2.x tags are still present:
https://github.com/intrepidcs/python_ics/blob/2eca369bf3825fe7032f77298cfecf070f98b504/setup.py#L98

... as a result, on a new Python2 Virtual Environment, when you attempt to install python-ics unrestricted, using pip, it tries to install python-ics 4.0.

**Comment by drebbe-intrepid** [comment]
Will look into this shortly. Thank you for finding this.

**Comment by drebbe-intrepid** [comment]
@ovianao I've committed the changes required in the source, I should have the binaries pushed to pypi by end of next week.

**Comment by ovianao** [comment]
@drebbe-intrepid, this is great.  Thanks very much!
