### ISSUE TITLE
[Questions] Application on Linux

### ISSUE THREAD

**Issue by freedeaths** [intrepidcs/python_ics#54]
OS: Ubuntu 18.04 LTS

Device: ValueCAN 3

1. icsneoapi:master + python_ics:v900

    * some functions not avaiable: I will get RuntimeError: retrieve function in icsneoapi.so when I use "ics.get_device_settings(device)" like #34
    * how to get out of blocked get_messages(): If there is no messages on bus, when I get into get_messages() function, it will be blocked and no ics.RuntimeError returns. How to deal with this situation? Is there a notice function who can tell me if there is msg in buffer? Or can I get a exception to get out? 

2. libicsneoc/libicsneolegacy (CMake from libicsneo:master)+ python_ics:v900

    * when I import ctypes and so = ctypes.CDLL("/abspath/libicsneoc.so") [or libicsneolegacy], when I use  so.icsneo_findAllDevices(), I will get segmentation fault (core dumped)
    * the same as import ics and ics.override_library_name("/abspath/libicsneoc.so") 

SO, What is the best practise to send and receive(non-blocked) with VCAN3 on Ubuntu 18.04 periodically?
THANK YOU VERY MUCH!

Eric

**Comment by drebbe-intrepid** [comment]
@freedeaths 
1.) Device settings are not supported in icsneoapi currently so there isn't a way to do this unfortunately. libicsneolegacy has support for device settings but doesn't have support for the replacement functions yet. We still need to add the following function for it to work in python_ics:

`icsneoGetDeviceSettingsType()`
`icsneoGetDeviceSettings()`
`icsneoSetDeviceSettings()`

A workaround would be doing the following: https://github.com/intrepidcs/python_ics/blob/v900/src/methods.cpp#L1826 Building python_ics v900 without USE_GENERIC_DEVICE_SETTINGS defined (defines.h needs to be modified to not set this).

`ics.get_messages()` has a timeout parameter you can set to 0 so it doesn't block. There isn't currently a way to tell if messages are in the queue.

2.) I would report the issue under the libicsneoapi repo with exact console output and as much distro information as possible.

**Comment by freedeaths** [comment]
@drebbe-intrepid
