### ISSUE TITLE
sent 15765 message with on valuecan

### ISSUE THREAD

**Issue by ep081106** [intrepidcs/python_ics#55]
hello
i think in the example "iso15765_example.py", it should be used 2 valuecan, could i use one valuecan to send and receive the message?
i tried to changed 
    tx_device = open_device(0)
    rx_device = open_device(1)
to
    tx_device = open_device(0)
    rx_device = open_device(0)
but it didn't work.

could you please give an example?

**Comment by drebbe-intrepid** [comment]
@ep081106: Sorry for the late response...

You would need to modify the example to use only one device:

```
device = open_device(0)
```

Change all instances of `tx_device` and `rx_device` to `device`

Modify netid to `ics.NETID_HSCAN2` for all functions where `rx_device` was.

Wire up a CAN network between CAN1 and CAN2 with termination resistors.

I would have to know more about your network setup to possibly give a better example.
