### ISSUE TITLE
Failed to open library: 'icsneo40.dll' with erro code: #193 or #126

### ISSUE THREAD

**Issue by createValue** [intrepidcs/python_ics#56]
The issue seems related to the 'icsneo40.dll'.
When I put the icsneo40.dll into C:\windows\system32\, it comes the error "Failed to open library: 'icsneo40.dll' with error code #193". When I delete the icsneo40.dll in the system32 folder, come out same message " Failed to open library: 'icsneo40.dll' with error code #126.
Tried to put the icsneo40.dll into C:\windows\SysWOW64\, it comes back the same error code #126.
I'm running on Windows 7 64bits system, and python3.7.
And tried different version icsneo40.dll, can not fix the issue.
Can anybody give me some guide? Thanks a lot.

**Comment by drebbe-intrepid** [comment]
@createValue 
#193 means ERROR_BAD_EXE_FORMAT. 
#126 means ERROR_MOD_NOT_FOUND.
https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

On a 64-bit Windows SysWOW64 is for 32-bit DLLs and system32 is for 64-bit DLLs (Thank Microsoft for this one).

You need to match up the interpreter with the DLL, more than likely your icsneo40.dll is 32-bit so use a 32-bit version of python.

**Comment by shinhwap** [comment]
@drebbe-intrepid 
Hello, I have the same problem.
If I install Vehicle Spy 3, program work.
But if I uninstall Vehicle Spy3, program show the same error above.
I have checked SysWOW64 is 32-bit DLL and system32 is 64-bit DLL.
Why should I need keep Vehicle Spy 3 installed in my computer?

**Comment by drebbe-intrepid** [comment]
@shinhwap You'll need to have Vehicle Spy 3 installed or at a bare minimum copy icsneo40.dll before you uninstall and recopy it back into SysWOW64/system32 directory. Please contact our support team for additional help: https://intrepidcs.com/support/contact-support/
