### ISSUE TITLE
icsneoWaitForRxMessagesWithTimeOut

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#59]
Hi @drebbe-intrepid, any reason why `icsneoWaitForRxMessagesWithTimeOut` is not implemented in python-ics?

I assume this could be more efficient than polling using `icsneoGetMessages`

**Comment by drebbe-intrepid** [comment]
@pierreluctg No reason in particular, its just the way I've personally done it for years. I'm assuming you are hitting a bottle neck somewhere with one of your setups?

**Comment by drebbe-intrepid** [comment]
@pierreluctg ignore the question, just seen the pull request.

**Comment by drebbe-intrepid** [comment]
@pierreluctg I'm going to add this as an enhancement unless you are having performance problem even after https://github.com/intrepidcs/python_ics/pull/58

**Comment by drebbe-intrepid** [comment]
Related: Issue #60

**Comment by drebbe-intrepid** [comment]
Closing this out.

Related: #84
