### ISSUE TITLE
ics.get_messages() GIL locking performance

### ISSUE THREAD

**Issue by drebbe-intrepid** [intrepidcs/python_ics#60]
When waiting for messages to come across the bus we lock and unlock the GIL needlessly every 1ms.

See Pull Request here for more details: https://github.com/intrepidcs/python_ics/pull/58

**Comment by drebbe-intrepid** [comment]
@pierreluctg

**Comment by drebbe-intrepid** [comment]
Don't close this until we merge this into 4.0 also.

**Comment by pierreluctg** [comment]
@drebbe-intrepid, please see #62, #63 and #64.

Thank you

**Comment by drebbe-intrepid** [comment]
@pierreluctg Merged, thank you for taking the time to do this! Are you in an immediate need for a release?

**Comment by pierreluctg** [comment]
@drebbe-intrepid it would be appreciated if you could push some release, yes.

We are using v803 mainly and will be moving to v900 soon.

Thank you

**Comment by pierreluctg** [comment]
@drebbe-intrepid is there anything I can do to accelerate this?

Thank you

**Comment by drebbe-intrepid** [comment]
@pierreluctg I'll make sure to do a release at the end of the day today.

**Comment by drebbe-intrepid** [comment]
@pierreluctg I didn't have time to do this yesterday, I'm going try and do it today.

**Comment by drebbe-intrepid** [comment]
@pierreluctg sorry for the delay, v3.2 (v803) and v4.3 (v900) are built and up on pip.

**Comment by pierreluctg** [comment]
Thank you @drebbe-intrepid
