### ISSUE TITLE
Support many different icsnVC40.h versions in one release

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#65]
@drebbe-intrepid would it be possible to to support many different icsnVC40.h versions in one release? Essentially keeping a copy of the structure for each versions and switch when we initialize the DLL.

The issue we have is that when we install a python package that depends in python-ics, there is not easy way to query the installed neoVI driver version and then choose the appropriate python-ics version.

In addition, there is not check in python-ics to alert (via warning or other type of logging) the user when the mismatched versions are in use.

Having a single release that is backward compatible would be the most user friendly option.

Driver version compatibility check when we initialize the DLL can alternatively be use to improve the user experience.

**Comment by drebbe-intrepid** [comment]
@pierreluctg Let me discuss internally and see what I can do here. I agree with everything here. Version 5.0 I rewrote all the structure handling so this should be a lot easier to manage something to work in between versions when something breaks backwards compatibility.

**Comment by drebbe-intrepid** [comment]
@pierreluctg After a lot of consideration and thinking about this there isn't much to actually do here. For the most part the API is fairly stable, even if you are using a newer version of the python_ics library it still should remain fairly backwards compatible with older versions. If there is something that is actually broken please generate a bug report and I'll fix it ASAP.

That being said I am breaking compatibility with the Find/Open functions starting with version 5.0 (not released yet) (Version 901 of Vehicle Spy). The new generator script spits out a JSON object I can easily compare, so if there are any breaking changes, I will be able to handle them / document the break.
