### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#67]
In one of our project migrating to python 3.8, ics is one of 3 top packages which not support Python 3.8. So please add 3.8 to support list. Thanks!

**Comment by drebbe-intrepid** [comment]
@keelung-yang I've uploaded v4.3 to pip. I did a quick check of the Python 3.8 change log and made sure I could at least call a few functions of the module, consider this experimental support for right now.

Thank you for reporting this, time has been flying by and I missed the release date!

**Comment by keelung-yang** [comment]
Thanks for your such quick fix. It saved me! Now we've only 2 packages left. THANK YOU VERY VERY MUCH!
