### ISSUE TITLE
undefined symbol in Ubuntu 18.04

### ISSUE THREAD

**Issue by layerthinker** [intrepidcs/python_ics#72]
Run following python command: 
import ics
ics.override_library_name("/usr/lib/x86_64-linux-gnu/libicsneolegacy.so")

Got error: 
override_library_name(): Failed to open library '//usr/lib/x86_64-linux-gnu/libicsneolegacy.so': /usr/lib/x86_64-linux-gnu/libicsneolegacy.so: undefined symbol: _ZN6icsneo6Device17SerialNumToStringB5cxx11Ej

**Comment by layerthinker** [comment]
This is the output with: 
cmake ..
-- Build type: RelWithDebInfo
-- Boost version: 1.65.1
-- Not generating API documentation
fatal: No annotated tags can describe '2a47b6f179699f67dc8c39634ea245c49b02ec0f'.
However, there were unannotated tags: try --tags.
-- Detected git snapshot version: unknown
-- Not building libftdi1++
-- Not building python bindings
-- ftdi_eeprom build is disabled
-- libConfuse not found, won't build ftdi_eeprom
-- NOT building unit test
-- Configuring done
-- Generating done
-- Build files have been written to: /libicsneo/build

**Comment by layerthinker** [comment]
Inspection results of shared object: 
$nm -D libicsneolegacy.so | grep _ZN6icsneo6Device17SerialNumToString
                 U _ZN6icsneo6Device17SerialNumToStringB5cxx11Ej
0000000000137378 T _ZN6icsneo6Device17SerialNumToStringEj

**Comment by drebbe-intrepid** [comment]
@layerthinker sorry for the late response but you would be better off posting this over at https://github.com/intrepidcs/libicsneo since it pertains to the libicsneo library.
