### ISSUE TITLE
Confused ISO15765 API name

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#73]
iso15765_transmit_message() is used to **transmit** msg.
iso15765_receive_message(), **receive** none of msg, but used to setup receiving msg.

So why not just _iso15765_setup_rx_msg_() or more generic _setup_rx_msg_(msg_type : iso15765/raw...) ?

**Comment by drebbe-intrepid** [comment]
I agree the name is confusing but its how the C API was written so its outside of the scope here.
