### ISSUE TITLE
st_cm_iso157652_tx_message/st_cm_iso157652_rx_message flags are not implemented.

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#74]
It's hard to memery bit positions in flags.
Maybe using python buildin IntEnum class is a good choose.

**Comment by drebbe-intrepid** [comment]
Updated example https://github.com/intrepidcs/python_ics/blob/master/examples/iso15765_example.py

References to the new structures:

- https://github.com/intrepidcs/python_ics/blob/master/ics/structures/st_cm_iso157652_tx_message.py
- https://github.com/intrepidcs/python_ics/blob/master/ics/structures/st_cm_iso157652_rx_message.py

**TODO:** This all still needs to be tested in master.

**Comment by drebbe-intrepid** [comment]
This will be tested before release, Documentation and flags have been implemented.
