### ISSUE TITLE
Add Data member to CmISO157652RxMessage

### ISSUE THREAD

**Issue by keelung-yang** [intrepidcs/python_ics#75]
Just like in CmISO157652TxMessage.

We need to combine SpyMessages into a ISO1576 message manually.
It's better to be done by python_ics package since this is generic to applications.

**Comment by drebbe-intrepid** [comment]
@keelung-yang Can you expand on this more and provide an example?

**Comment by drebbe-intrepid** [comment]
I'm going to close this out, please feel free to open this again in the future if needed.
