### ISSUE TITLE
Using correct value type in coremini read/write app signal

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#88]
meth_coremini_read_app_signal isincorrectly returning a python int instead of a python float. The double to python int conversion was resulting in always returning 0.

meth_coremini_write_app_signa isincorrectly taking a python int for the value argument instead of a python float.

**Comment by drebbe-intrepid** [comment]
Thanks for catching this.

**Comment by drebbe-intrepid** [comment]
Leaving open so I can merge into newer branches at a later date.

**Comment by drebbe-intrepid** [comment]
https://github.com/intrepidcs/python_ics/releases/tag/v4.6
