### ISSUE TITLE
while only one message sent,Get two messges from the methon  ics.get_messages()，pyhon ics 4.6

### ISSUE THREAD

**Issue by changmaifan** [intrepidcs/python_ics#89]
with the python-ics4.6, send only one message ,but get two same messages from the the methon ics.get_messages().
ics.iso15765_transmit_message
0x760 0x2 0x10 0x3

ics.get_messages().
0x760  0x2 0x10 0x3
0x768  0x6 0x50 0x3
0x760  0x2 0x10 0x3
0x768  0x6 0x50 0x3

**Comment by drebbe-intrepid** [comment]
@changmaifan Can you provide more information here?

- Source code
- Hardware setup (What intrepid hardware and what its attached to)
- Operating System
- icsneo40.dll version (libicsneo if on linux)

**Comment by drebbe-intrepid** [comment]
I'm going to assume this is a non-issue as there has been no response for about 5 months. Feel free to re-open this if needed.
