### ISSUE TITLE
fail build with build_all.bat with Python3.6

### ISSUE THREAD

**Issue by telehan** [intrepidcs/python_ics#9]
fail build with build_all.bat with Python3.6
 （Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)] on win32）

the build_all.bat make some change according to python location path.

`set py36dir=D:\Python\Python36-32

%py36dir%\Scripts\pip install wheel twine

%py36dir%\Scripts\pip install wheel twine

%py36dir%\python setup.py sdist bdist_wheel

%py36dir%\python setup.py sdist bdist_wheel

%py36dir%\scripts\twine upload dist/* -r pypitest`

the error message looks like:
......
building 'ics' extension
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMAJOR_VERSION=2 -DMINOR_VERSION=8 -Iinclude -Iinclude/ics -Iinclude/ice -ID:\Python\Python36-32\include -ID:\Python\Python36-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt" /EHsc /Tpsrc\._defines.cpp /Fobuild\temp.win32-3.6\Release\src\._defines.obj
._defines.cpp
src\._defines.cpp: warning C4821: 无法确定 Unicode 编码类型，请用签名(BOM)保存文件
src\._defines.cpp: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
src\._defines.cpp(1): error C2018: 未知字符“0x5”
src\._defines.cpp(1): error C2018: 未知字符“0x16”
src\._defines.cpp(1): error C2018: 未知字符“0x7”
src\._defines.cpp(1): error C2018: 未知字符“0x2”
src\._defines.cpp(1): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
src\._defines.cpp(1): error C2146: 语法错误: 缺少“;”(在标识符“OS”的前面)
src\._defines.cpp(1): error C2059: 语法错误:“数字上的错误后缀”
src\._defines.cpp(1): error C2018: 未知字符“0xe”
src\._defines.cpp(1): error C2018: 未知字符“0x1”
src\._defines.cpp(1): error C2018: 未知字符“0x1e”
src\._defines.cpp(1): error C2059: 语法错误:“?”
src\._defines.cpp(1): error C2018: 未知字符“0x15”
src\._defines.cpp(1): error C3927: "->": 非函数声明符后不允许尾随返回类型
src\._defines.cpp(1): error C3484: 语法错误: 返回类型前应为“->”
src\._defines.cpp(1): error C3613: “->”后缺少返回类型(假定为“int”)
src\._defines.cpp(1): error C2146: 语法错误: 缺少“;”(在标识符“apple”的前面)
src\._defines.cpp(1): error C2059: 语法错误:“user-defined literal”
src\._defines.cpp(1): error C2018: 未知字符“0x1c”
src\._defines.cpp(1): error C3873: “0xf8f5”: 不允许将此字符作为标识符的第一个字符
src\._defines.cpp(1): error C3872: “0xf8f5”: 此字符不允许在标识符中使用
error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
......

**Comment by drebbe-intrepid** [comment]
This is a script I use for uploading to pypi. Use pip to install, not this script.
