### ISSUE TITLE
Need detailed documentation about CmISO157652TxMessage.flags and CmISO157652RxMessage.flags 

### ISSUE THREAD

**Issue by alwaysberay** [intrepidcs/python_ics#92]
Need detailed documentation about CmISO157652TxMessage.flags and CmISO157652RxMessage.flags

**Comment by drebbe-intrepid** [comment]
See:
TX:
https://github.com/intrepidcs/python_ics/blob/master/examples/iso15765_example.py#L68
https://github.com/intrepidcs/python_ics/blob/master/include/ics/icsnVC40.h#L3351
https://cdn.intrepidcs.net/support/neoVIDLL/ISO15765TxMessage.htm

RX:
https://github.com/intrepidcs/python_ics/blob/master/examples/iso15765_example.py#L96
https://github.com/intrepidcs/python_ics/blob/master/include/ics/icsnVC40.h#L3424
https://cdn.intrepidcs.net/support/neoVIDLL/ISO15765RxMessage.htm

Documentation is lacking on the python side of this.

**Comment by drebbe-intrepid** [comment]
Also future versions are going to break old behavior and include the bitfields:

https://github.com/intrepidcs/python_ics/blob/master/ics/structures/st_cm_iso157652_tx_message.py
https://github.com/intrepidcs/python_ics/blob/master/ics/structures/st_cm_iso157652_rx_message.py

I have some blockers I need to fix before I can a new release out.
