### ISSUE TITLE
Broken compatibility with libicsneo

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#96]
With the commit https://github.com/intrepidcs/python_ics/commit/f09909e70a23dff99a0b9a99c5a54c74c58b9239, the move to from `icsneoOpenNeoDevice` to `icsneoOpenDevice` the compatibility with `libicsneolegacy.so` is broken.

`icsneoOpenDevice` is not present in `libicsneolegacy.so`.

**Comment by hollinsky-intrepid** [comment]
We're all set here, thanks @drebbe-intrepid and @pierreluctg!

**Comment by drebbe-intrepid** [comment]
@pierreluctg I'll let you close this out, I did test this under Ubuntu with two vcan4.4s.

**Comment by pierreluctg** [comment]
Tested on Ubuntu 20.04

Thank you @drebbe-intrepid  and @hollinsky-intrepid.
