### ISSUE TITLE
Exception changed in version 903.17

### ISSUE THREAD

**Issue by pierreluctg** [intrepidcs/python_ics#97]
Since version 903.17, the `RuntimeError` changed location.

This sample code will produce different exception in version 4.6 (and prior) and version 903.17 (and newer).

```python
import ics
ics.open_device(-1)    # Cause a RuntimeError
```

With python-ics 4.6,  we get `ics.RuntimeError: Error: open_device(): Failed to find a device to open.`
With python-ics 903.17, we get `ics.ics.RuntimeError: Error: open_device(): Failed to find a device to open.`

The path of the `RuntimeError` change from `ics.RuntimeError` to `ics.ics.RuntimeError`

**Comment by drebbe-intrepid** [comment]
This is an under the hood change. All the original APIs from the c module code have been moved to `ics.ics`. Its very dirty but had to be done since I'm mixing pure python code with c module that need to have the same module namespace.

This should still be functional and backwards compatible:
```
try:
    import ics
    ics.open_device(-1)    # Cause a RuntimeError
except ics.RuntimeError as ex:
    print(ex)
```

**Comment by drebbe-intrepid** [comment]
```
>>> import ics
>>> ics.RuntimeError
<class 'ics.ics.RuntimeError'>
>>> try:
...     ics.open_device(-1)
... except ics.RuntimeError as ex:
...     print(ex)
...
Error: open_device(): Failed to find a device to open.
```

**Comment by drebbe-intrepid** [comment]
All the "magic" is done in the init file here:

https://github.com/intrepidcs/python_ics/blob/master/ics/__init__.py

**Comment by pierreluctg** [comment]
Thank you @drebbe-intrepid.
